### ISSUE TITLE
Error: marker was not found

### ISSUE THREAD

**Issue by pawelotto** [lolPants/image-hash#1]
Funny thing, I'm running this to generate hash on the very same picture and sometimes it runs OK then it mysteriously fails on the same image:

`Error: marker was not found
    at decodeScan (/home/po/dev/myproject/myproject-dir/node_modules/jpeg-js/lib/decoder.js:324:15)
    at constructor.parse (/home/po/dev/myproject/myproject-dir/node_modules/jpeg-js/lib/decoder.js:744:29)
    at Object.decode (/home/po/dev/myproject/myproject-dir/node_modules/jpeg-js/lib/decoder.js:1004:11)
    at readImageData (/home/po/dev/myproject/myproject-dir/node_modules/@lolpants/image-hash/lib/index.js:19:89)
    at Object.exports.imageHash (/home/po/dev/myproject/myproject-dir/node_modules/@lolpants/image-hash/lib/index.js:25:18)
    at exports.default (/home/po/dev/myproject/myproject-dir/dist/func/image-hash.js:16:29)
    at Transform.transform [as _transform] (/home/po/dev/myproject/myproject-dir/dist/stream/transform.js:11:34)
    at Transform._read (_stream_transform.js:187:10)
    at Transform._write (_stream_transform.js:175:12)
    at doWrite (_stream_writable.js:415:12)`

**Comment by pawelotto** [comment]
OK I figured this out, this isn't your module's fault. the _chokidar_ file watcher was streaming filenames too quickly (before the files fully loaded), that's why the error.
